Restrict the version of mongoose.
mongoose 3.9.3 or more depends on mongodb 1.4.12.
mongodb 1.4.12 has a bug that executing listIndexes()
causes an exception like below by retrieving indexes
from an unknown collection.

crowi/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (crowi/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
    at crowi/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
    at crowi/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
    at crowi/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at Server.Base._callHandler (crowi/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at crowi/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (crowi/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (crowi/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emit (events.js:107:17)
    at null.<anonymous> (crowi/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)